CROSS_COMPILE ?=
CC = $(CROSS_COMPILE)gcc

TARGET = writer
SRCS = writer.c
OBJS = $(SRCS:.c=.o)
CFLAGS = -Wall

all: $(TARGET)
$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)
